name: Check build

on:
  pull_request:
  schedule:
    - cron: 0 20 * * 5

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        platform: [x64, x86]
        build_type: [release, debug]
        exclude:
          - os: macOS-latest
            platform: x86
          - os: ubuntu-latest
            platform: x86

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install googletest
        if: contains(matrix.os, 'macOS') || contains(matrix.os, 'ubuntu')
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -DBUILD_GMOCK=OFF -DCMAKE_CXX_STANDARD=11 .
          sudo make -k -j all install

      - name: Restore nuget packages (Windows)
        if: contains(matrix.os, 'windows')
        run: |
          nuget restore build/win_vs/libsatop/libsatop.sln

      - name: Build tests (Ubuntu, macOS)
        if: contains(matrix.os, 'macOS') || contains(matrix.os, 'ubuntu')
        run: |
          make BUILD_TYPE=${{ matrix.build_type }} -k -j build-test

      - name: Build tests (Windows)
        if: contains(matrix.os, 'windows')
        run: |
          msbuild build/win_vs/libsatop/libsatop_test/libsatop_test.vcxproj /t:build /p:Configuration=${{ matrix.build_type }} /p:Platform="${{ matrix.platform }}" /maxCpuCount

      - name: Run tests (Ubuntu, macOS)
        if: contains(matrix.os, 'macOS') || contains(matrix.os, 'ubuntu')
        run: |
          make BUILD_TYPE=${{ matrix.build_type }} -k -j run-test

      - name: Run tests (Windows)
        if: contains(matrix.os, 'windows')
        run: |
          out\\${{ matrix.platform }}\\${{ matrix.build_type }}\\libsatop_test\\libsatop_test.exe

      - name: Test `make clean` works fine (Ubuntu, macOS)
        if: contains(matrix.os, 'macOS') || contains(matrix.os, 'ubuntu')
        run: |
          make BUILD_TYPE=${{ matrix.build_type }} -k -j clean
